apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: hazitgi/next-kanban-dashboard-client
          imagePullPolicy: IfNotPresent
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: https://posts.com/api
            - name: NEXT_SOCKET_URL
              value: https://posts.com


---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
