apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: node:20-alpine
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:root@task-manager-db:5432/task_manager"
      restartPolicy: OnFailure
