# notification-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: hazitgi/notifications
          ports:
            - containerPort: 5000
          env:
            - name: NATS_CLUSTER_ID
              value: task_manager
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - name: notifications
      protocol: TCP
      port: 4000
      targetPort: 4000

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: notification-nodeport-service
# spec:
#   ports:
#     - port: 4000
#       targetPort: 4000
#       nodePort: 30001 # You can specify your preferred node port here
#   selector:
#     app: notification-service
#   type: NodePort
