apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-service
  template:
    metadata:
      labels:
        app: task-manager-service
    spec:
      containers:
        - name: task-manager-service
          image: hazitgi/task
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:root@task-manager-db:5432/task_manager"
            - name: NATS_CLUSTER_ID
              value: task_manager
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: task-manager-service
